version: "2"
services:
  db:
    image: postgres:10
    env_file: env_file
    expose:
      - 5432
    networks:
      - db_nw
  app:
    build: .
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
    env_file:
      - env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
  web:
    image: nginx:1.13.5
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - app
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
